CREATE TABLE DKPB (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100),
  AREA_ID VARCHAR(50),
  PERIODE INT,
  VERIFIED_OLEH VARCHAR(100),
  VERIFIED_TANGGAL DATE,
  APPROVED_OLEH VARCHAR(100),
  APPROVED_TANGGAL DATE,
  UPLOADED_OLEH VARCHAR(20),
  CREATED_AT DATETIME,
  COUNTER INT,
  STATUS VARCHAR(50)
);

CREATE TABLE LOG (
  DKPB_ID INT,
  UPLOADER INT,
  VIEWER INT,
  STATUS INT,
  MESSAGE VARCHAR(255),
  CREATED_AT DATETIME
);

CREATE TABLE UPLOAD (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100),
  PATH VARCHAR(255),
  DKPB_ID INT,
  PERIODE INT
);

CREATE TABLE DKPB_DETAILS (
  DKPB_ID INT,
  ID INT PRIMARY KEY,
  KATEGORI_BANGUNAN VARCHAR(100),
  KOMPONEN_ID INT,
  MATERIAL_ID INT,
  VALUE FLOAT
);

CREATE TABLE USER (
  NIP VARCHAR(20) PRIMARY KEY,
  UNIT_KANTOR VARCHAR(100)
);

CREATE TABLE MATERIALDETAIL (
  ID INT PRIMARY KEY,
  MATERIAL_ID INT,
  HARGA FLOAT,
  KOEFISIEN FLOAT,
  PERIODE INT,
  ID_AREA INT,
  CREATED_AT DATETIME,
  UPDATED_AT DATETIME
);

CREATE TABLE MODELBANGUNAN (
  ID INT PRIMARY KEY,
  NAME VARCHAR(100),
  ID_AREA INT,
  DKPB_ID INT
);

CREATE TABLE MODELBANGUNANDETAILS (
  MODELBANGUNAN_ID INT,
  LANTAI VARCHAR(50),
  LUAS FLOAT,
  BASEMENT INT,
  KONDISI_TANAH INT,
  MASTER_MODEL INT
);

CREATE TABLE MASTERKONDISITANAH (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100),
  KOEFISIEN FLOAT,
  PERIODE INT
);

CREATE TABLE MASTERLANTAI (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100),
  KOEFISIEN FLOAT,
  PERIODE INT
);

CREATE TABLE MASTERLISTRIK (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100),
  HARGA FLOAT,
  PERIODE INT
);

CREATE TABLE MASTERMATERIAL (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100),
  CREATED_AT DATETIME,
  UPDATED_AT DATETIME,
  KOMPONEN_ID INT
);

CREATE TABLE MASTERKOMPONEN (
  ID INT PRIMARY KEY,
  NAMA VARCHAR(100)
);

CREATE TABLE MASTERKATEGORIBANGUNAN (
  ID INT PRIMARY KEY,
  KODE VARCHAR(50),
  NAMA VARCHAR(100)
);

CREATE TABLE MASTERAREA (
  ID INT PRIMARY KEY,
  KOTA VARCHAR(100),
  KPKNL VARCHAR(100)
);

CREATE TABLE MASTERMODEL (
  ID INT PRIMARY KEY,
  KATEGORI_BANGUNAN INT,
  STRUKTUR_BAWAH INT,
  STRUKTUR_RANGKA INT,
  STRUKTUR_ATAP INT,
  ATAP INT,
  DINDING INT,
  LANGIT_LANGIT INT,
  LANTAI INT,
  INSTALASI_AIR INT,
  INSTALASI_LISTRIK INT,
  PENYAMBUNGAN INT,
  PELAPIS_DINDING INT
);

CREATE TABLE SNBA (
  ID INT PRIMARY KEY,
  INPUT VARCHAR(255),
  SNBA FLOAT,
  APPROVED_OLEH INT,
  APPROVED_DATE DATE,
  SEND_DATE DATE,
  SEND_STATUS INT
);

CREATE TABLE BIAYATIDAKLANGSUNG (
    ID INT,
    NAMA VARCHAR(100),
    KOEFISIEN FLOAT
);