CREATE TABLE DKPB (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100),
  AREA_ID VARCHAR2(50),
  PERIODE NUMBER,
  VERIFIED_OLEH VARCHAR2(100),
  VERIFIED_TANGGAL DATE,
  APPROVED_OLEH VARCHAR2(100),
  APPROVED_TANGGAL DATE,
  UPLOADED_OLEH VARCHAR2(20),
  CREATED_AT DATE,
  COUNTER NUMBER,
  STATUS VARCHAR2(50)
);

CREATE TABLE LOG (
  DKPB_ID NUMBER,
  UPLOADER NUMBER,
  VIEWER NUMBER,
  STATUS NUMBER,
  MESSAGE VARCHAR2(255),
  CREATED_AT DATE,
);

CREATE TABLE UPLOAD (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100),
  PATH VARCHAR2(255),
  DKPB_ID NUMBER,
  PERIODE NUMBER,
);

CREATE TABLE DKPB_DETAILS (
  DKPB_ID NUMBER,
  ID NUMBER PRIMARY KEY,
  KATEGORI_BANGUNAN VARCHAR2(100),
  KOMPONEN_ID NUMBER,
  MATERIAL_ID NUMBER,
  VALUE FLOAT,
);

CREATE TABLE USER (
  NIP VARCHAR2(20) PRIMARY KEY,
  UNIT_KANTOR VARCHAR2(100)
);

CREATE TABLE MATERIALDETAIL (
  ID NUMBER PRIMARY KEY,
  MATERIAL_ID NUMBER,
  HARGA FLOAT,
  KOEFISIEN FLOAT,
  PERIODE NUMBER,
  ID_AREA NUMBER,
  CREATED_AT DATE,
  UPDATED_AT DATE
);

CREATE TABLE MODELBANGUNAN (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100),
  ID_AREA NUMBER,
  DKPB_ID NUMBER,
);

CREATE TABLE MODELBANGUNANDETAILS (
  MODELBANGUNAN_ID NUMBER,
  LANTAI VARCHAR2(50),
  LUAS FLOAT,
  BASEMENT NUMBER,
  KONDISI_TANAH NUMBER,
  MASTER_MODEL NUMBER,
);

CREATE TABLE MASTERKONDISITANAH (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100),
  KOEFISIEN FLOAT,
  PERIODE NUMBER
);

CREATE TABLE MASTERLANTAI (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100),
  KOEFISIEN FLOAT,
  PERIODE NUMBER
);

CREATE TABLE MASTERLISTRIK (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100),
  HARGA FLOAT,
  PERIODE NUMBER
);

CREATE TABLE MASTERMATERIAL (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100),
  CREATED_AT DATE,
  UPDATED_AT DATE,
  KOMPONEN_ID NUMBER,
);

CREATE TABLE MASTERKOMPONEN (
  ID NUMBER PRIMARY KEY,
  NAMA VARCHAR2(100)
);

CREATE TABLE MASTERKATEGORIBANGUNAN (
  ID NUMBER PRIMARY KEY,
  KODE VARCHAR2(50),
  NAMA VARCHAR2(100)
);

CREATE TABLE MASTERAREA (
  ID NUMBER PRIMARY KEY,
  KOTA VARCHAR2(100),
  KPKNL VARCHAR2(100)
);

CREATE TABLE MASTERMODEL (
  ID NUMBER PRIMARY KEY,
  KATEGORI_BANGUNAN NUMBER,
  STRUKTUR_BAWAH NUMBER,
  STRUKTUR_RANGKA NUMBER,
  STRUKTUR_ATAP NUMBER,
  ATAP NUMBER,
  DINDING NUMBER,
  LANGIT_LANGIT NUMBER,
  LANTAI NUMBER,
  INSTALASI_AIR NUMBER,
  INSTALASI_LISTRIK NUMBER,
  PENYAMBUNGAN NUMBER,
  PELAPIS_DINDING NUMBER
);

CREATE TABLE SNBA (
  ID NUMBER PRIMARY KEY,
  INPUT VARCHAR2(255),
  SNBA FLOAT,
  APPROVED_OLEH NUMBER,
  APPROVED_DATE DATE,
  SEND_DATE DATE,
  SEND_STATUS NUMBER
);

--- oracle 
create table BIAYATIDAKLANGSUNG (
    ID NUMBER,
    NAME VARCHAR2(100),
    KOEFISIEN FLOAT
)