INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (353,'Kab. Sumba Timur',' KPKNL Kupang'),
	 (354,'Kab. Timor Tengah Selatan',' KPKNL Kupang'),
	 (355,'Kab. Timor Tengah Utara',' KPKNL Kupang'),
	 (356,'Kab. Rote Ndao',' KPKNL Kupang'),
	 (357,'Kab. Sabu Raijua',' KPKNL Kupang'),
	 (358,'Kab. Sikka',' KPKNL Kupang'),
	 (359,'Kab. Lembata',' KPKNL Kupang'),
	 (360,'Kab. Ende',' KPKNL Kupang'),
	 (361,'Kab. Flores Timur',' KPKNL Kupang'),
	 (362,'Kab. Manggarai',' KPKNL Kupang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (363,'Kab. Manggarai Barat',' KPKNL Kupang'),
	 (364,'Kab. Ngada',' KPKNL Kupang'),
	 (365,'Kab. Nagekeo',' KPKNL Kupang'),
	 (366,'Kab. Manggarai Timur',' KPKNL Kupang'),
	 (367,'Kota Makassar','KPKNL Makassar'),
	 (368,'Kab. Bantaeng','KPKNL Makassar'),
	 (369,'Kab. Bulukumba','KPKNL Makassar'),
	 (370,'Kab. Gowa','KPKNL Makassar'),
	 (371,'Kab. Jeneponto','KPKNL Makassar'),
	 (372,'Kab. Maros','KPKNL Makassar');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (373,'Kab. Pangkajene dan Kepulauan','KPKNL Makassar'),
	 (374,'Kab. Kepulauan Selayar','KPKNL Makassar'),
	 (375,'Kab. Sinjai','KPKNL Makassar'),
	 (376,'Kab. Takalar','KPKNL Makassar'),
	 (377,'Kota Parepare','KPKNL Parepare'),
	 (378,'Kab. Barru','KPKNL Parepare'),
	 (379,'Kab. Pinrang','KPKNL Parepare'),
	 (380,'Kab. Sidenreng Rappang','KPKNL Parepare'),
	 (381,'Kab. Soppeng','KPKNL Parepare'),
	 (382,'Kab. Wajo','KPKNL Parepare');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (383,'Kab. Bone','KPKNL Parepare'),
	 (384,'Kota Palopo',' KPKNL Palopo'),
	 (385,'Kab. Luwu',' KPKNL Palopo'),
	 (386,'Kab. Luwu Utara',' KPKNL Palopo'),
	 (387,'Kab. Luwu Timur',' KPKNL Palopo'),
	 (388,'Kab. Tana Toraja',' KPKNL Palopo'),
	 (389,'Kab. Toraja Utara',' KPKNL Palopo'),
	 (390,'Kab. Enrekang',' KPKNL Palopo'),
	 (391,'Kota Kendari','KPKNL Kendari'),
	 (392,'Kab. Kolaka','KPKNL Kendari');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (393,'Kab. Kolaka Utara','KPKNL Kendari'),
	 (394,'Kab. Kolaka Timur','KPKNL Kendari'),
	 (395,'Kab. Konawe','KPKNL Kendari'),
	 (396,'Kab. Konawe Selatan','KPKNL Kendari'),
	 (397,'Kab. Konawe Utara','KPKNL Kendari'),
	 (398,'Kab. Bombana','KPKNL Kendari'),
	 (399,'Kota Baubau','KPKNL Kendari'),
	 (400,'Kab. Buton','KPKNL Kendari'),
	 (401,'Kab. Buton Utara','KPKNL Kendari'),
	 (402,'Kab. Muna','KPKNL Kendari');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (403,'Kab. Wakatobi','KPKNL Kendari'),
	 (404,'Kab. Buton Selatan','KPKNL Kendari'),
	 (405,'Kab. Buton Tengah','KPKNL Kendari'),
	 (406,'Kab. Konawe Kepulauan','KPKNL Kendari'),
	 (407,'Kab. Muna Barat','KPKNL Kendari'),
	 (408,'Kab. Mamuju','KPKNL Mamuju'),
	 (409,'Kab. Mamuju Tengah','KPKNL Mamuju'),
	 (410,'Kab. Pasangkayu','KPKNL Mamuju'),
	 (411,'Kab. Majene','KPKNL Mamuju'),
	 (412,'Kab. Polewali Mandar','KPKNL Mamuju');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (413,'Kab. Mamasa','KPKNL Mamuju'),
	 (414,'Kota Manado','KPKNL Manado'),
	 (415,'Kab. Minahasa','KPKNL Manado'),
	 (416,'Kab. Minahasa Utara','KPKNL Manado'),
	 (417,'Kab. Minahasa Tenggara','KPKNL Manado'),
	 (418,'Kab. Minahasa Selatan','KPKNL Manado'),
	 (419,'Kab. Bolaang Mongondow','KPKNL Manado'),
	 (420,'Kab. Bolaang Mongondow Utara','KPKNL Manado'),
	 (421,'Kab. Bolaang Mongondow Timur','KPKNL Manado'),
	 (422,'Kab. Bolaang Mongondow Selatan','KPKNL Manado');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (423,'Kota Bitung','KPKNL Manado'),
	 (424,'Kota Tomohon','KPKNL Manado'),
	 (425,'Kota Kotamobagu','KPKNL Manado'),
	 (426,'Kab. Kepulauan Sangihe','KPKNL Manado'),
	 (427,'Kab. Kepulauan Talaud','KPKNL Manado'),
	 (428,'Kab. Kepulauan Siau Tagulandang Biaro','KPKNL Manado'),
	 (429,'Kota Palu','KPKNL Palu'),
	 (430,'Kab. Buol','KPKNL Palu'),
	 (431,'Kab. Tolitoli','KPKNL Palu'),
	 (432,'Kab. Donggala','KPKNL Palu');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (433,'Kab. Parigi Moutong','KPKNL Palu'),
	 (434,'Kab. Morowali','KPKNL Palu'),
	 (435,'Kab. Banggai','KPKNL Palu'),
	 (436,'Kab. Banggai Kepulauan','KPKNL Palu'),
	 (437,'Kab. Banggai Laut','KPKNL Palu'),
	 (438,'Kab. Poso','KPKNL Palu'),
	 (439,'Kab. Tojo Una Una','KPKNL Palu'),
	 (440,'Kab. Sigi','KPKNL Palu'),
	 (441,'Kab. Morowali Utara','KPKNL Palu'),
	 (442,'Kota Gorontalo','KPKNL Gorontalo');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (443,'Kab. Gorontalo','KPKNL Gorontalo'),
	 (444,'Kab. Gorontalo Utara','KPKNL Gorontalo'),
	 (445,'Kab. Boalemo','KPKNL Gorontalo'),
	 (446,'Kab. Bone Bolango','KPKNL Gorontalo'),
	 (447,'Kab. Pohuwato','KPKNL Gorontalo'),
	 (448,'Kota Ternate','KPKNL Ternate'),
	 (449,'Kab. Halmahera Tengah','KPKNL Ternate'),
	 (450,'Kab. Halmahera Barat','KPKNL Ternate'),
	 (451,'Kab. Halmahera Timur','KPKNL Ternate'),
	 (452,'Kab. Halmahera Selatan','KPKNL Ternate');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (453,'Kab. Halmahera Utara','KPKNL Ternate'),
	 (454,'Kota Tidore Kepulauan','KPKNL Ternate'),
	 (455,'Kab. Kepulauan Sula','KPKNL Ternate'),
	 (456,'Kab. Pulau Taliabu','KPKNL Ternate'),
	 (457,'Kab. Pulau Morotai','KPKNL Ternate'),
	 (458,'Kota Jayapura','KPKNL Jayapura'),
	 (459,'Kab. Jayapura','KPKNL Jayapura'),
	 (460,'Kab. Jayawijaya','KPKNL Jayapura'),
	 (461,'Kab. Merauke','KPKNL Jayapura'),
	 (462,'Kab. Puncak Jaya','KPKNL Jayapura');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (463,'Kab. Sarmi','KPKNL Jayapura'),
	 (464,'Kab. Keerom','KPKNL Jayapura'),
	 (465,'Kab. Yahukimo','KPKNL Jayapura'),
	 (466,'Kab. Pegunungan Bintang','KPKNL Jayapura'),
	 (467,'Kab. Tolikara','KPKNL Jayapura'),
	 (468,'Kab. Boven Digoel','KPKNL Jayapura'),
	 (469,'Kab. Mappi','KPKNL Jayapura'),
	 (470,'Kab. Asmat','KPKNL Jayapura'),
	 (471,'Kab. Mamberamo Raya','KPKNL Jayapura'),
	 (472,'Kab. Mamberamo Tengah','KPKNL Jayapura');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (473,'Kab. Puncak','KPKNL Jayapura'),
	 (474,'Kab. Lanny Jaya','KPKNL Jayapura'),
	 (475,'Kab. Nduga','KPKNL Jayapura'),
	 (476,'Kab. Yalimo','KPKNL Jayapura'),
	 (477,'Kab. Mimika','KPKNL Jayapura'),
	 (478,'Kab. Biak Numfor','KPKNL Biak'),
	 (479,'Kab. Supiori','KPKNL Biak'),
	 (480,'Kab. Kepulauan Yapen','KPKNL Biak'),
	 (481,'Kab. Waropen','KPKNL Biak'),
	 (482,'Kab. Nabire','KPKNL Biak');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (483,'Kab. Paniai','KPKNL Biak'),
	 (484,'Kab. Deiyai','KPKNL Biak'),
	 (485,'Kab. Dogiyai','KPKNL Biak'),
	 (486,'Kab. Intan Jaya','KPKNL Biak'),
	 (487,'Kota Sorong','KPKNL Sorong'),
	 (488,'Kab. Sorong','KPKNL Sorong'),
	 (489,'Kab. Sorong Selatan','KPKNL Sorong'),
	 (490,'Kab. Fakfak','KPKNL Sorong'),
	 (491,'Kab. Tambrauw','KPKNL Sorong'),
	 (492,'Kab. Raja Ampat','KPKNL Sorong');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (493,'Kab. Maybrat','KPKNL Sorong'),
	 (494,'Kab. Manokwari','KPKNL Sorong'),
	 (495,'Kab. Teluk Bintuni','KPKNL Sorong'),
	 (496,'Kab. Kaimana','KPKNL Sorong'),
	 (497,'Kab. Teluk Wondama','KPKNL Sorong'),
	 (498,'Kab. Manokwari Selatan','KPKNL Sorong'),
	 (499,'Kab. Pegunungan Arfak','KPKNL Sorong'),
	 (500,'Kota Ambon','KPKNL Ambon'),
	 (501,'Kab. Kepulauan Tanimbar','KPKNL Ambon'),
	 (502,'Kab. Maluku Tengah','KPKNL Ambon');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (503,'Kab. Maluku Tenggara','KPKNL Ambon'),
	 (504,'Kab. Maluku Barat Daya','KPKNL Ambon'),
	 (505,'Kota Tual','KPKNL Ambon'),
	 (506,'Kab. Buru','KPKNL Ambon'),
	 (507,'Kab. Buru Selatan','KPKNL Ambon'),
	 (508,'Kab. Seram Bagian Barat','KPKNL Ambon'),
	 (509,'Kab. Seram Bagian Timur','KPKNL Ambon'),
	 (510,'Kab. Kepulauan Aru','KPKNL Ambon'),
	 (3,'Kab. Pidie','KPKNL Banda Aceh'),
	 (1,'Kota Banda Aceh','KPKNL Banda Aceh');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (2,'Kota Sabang','KPKNL Banda Aceh'),
	 (4,'Kab. Pidie Jaya','KPKNL Banda Aceh'),
	 (5,'Kab. Aceh Besar','KPKNL Banda Aceh'),
	 (6,'Kab. Aceh Barat','KPKNL Banda Aceh'),
	 (7,'Kab. Aceh Selatan','KPKNL Banda Aceh'),
	 (8,'Kab. Aceh Singkil','KPKNL Banda Aceh'),
	 (9,'Kab. Aceh Jaya','KPKNL Banda Aceh'),
	 (10,'Kab. Aceh Barat Daya','KPKNL Banda Aceh'),
	 (11,'Kab. Simeulue','KPKNL Banda Aceh'),
	 (12,'Kota Subulussalam','KPKNL Banda Aceh');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (13,'Kab. Nagan Raya','KPKNL Banda Aceh'),
	 (14,'Kota Lhokseumawe','KPKNL Lhokseumawe'),
	 (15,'Kab. Aceh Utara','KPKNL Lhokseumawe'),
	 (16,'Kab. Aceh Tengah','KPKNL Lhokseumawe'),
	 (17,'Kab. Aceh Timur','KPKNL Lhokseumawe'),
	 (18,'Kab. Aceh Tamiang','KPKNL Lhokseumawe'),
	 (19,'Kab. Aceh Tenggara','KPKNL Lhokseumawe'),
	 (20,'Kab. Bireuen','KPKNL Lhokseumawe'),
	 (21,'Kota Langsa','KPKNL Lhokseumawe'),
	 (22,'Kab. Bener Meriah','KPKNL Lhokseumawe');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (23,'Kab. Gayo Lues','KPKNL Lhokseumawe'),
	 (24,'Kota Medan','KPKNL Medan'),
	 (25,'Kab. Deli Serdang','KPKNL Medan'),
	 (26,'Kab. Serdang Bedagai','KPKNL Medan'),
	 (27,'Kota Binjai','KPKNL Medan'),
	 (28,'Kab. Langkat','KPKNL Medan'),
	 (29,'Kab. Karo','KPKNL Medan'),
	 (30,'Kota Pematang Siantar','KPKNL Pematang Siantar'),
	 (31,'Kota Tebing Tinggi','KPKNL Pematang Siantar'),
	 (32,'Kab. Samosir','KPKNL Pematang Siantar');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (33,'Kab. Toba Samosir','KPKNL Pematang Siantar'),
	 (34,'Kab. Dairi','KPKNL Pematang Siantar'),
	 (35,'Kab. Pakpak Bharat','KPKNL Pematang Siantar'),
	 (36,'Kab. Asahan','KPKNL Kisaran'),
	 (37,'Kota Tanjung Balai','KPKNL Kisaran'),
	 (38,'Kab. Labuhanbatu','KPKNL Kisaran'),
	 (39,'Kab. Labuhanbatu Utara','KPKNL Kisaran'),
	 (40,'Kab. Labuhanbatu Selatan','KPKNL Kisaran'),
	 (41,'Kab. Batu Bara','KPKNL Kisaran'),
	 (42,'Kota Padangsidimpuan','KPKNL Padangsidimpuan');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (43,'Kab. Tapanuli Tengah','KPKNL Padangsidimpuan'),
	 (44,'Kab. Tapanuli Utara','KPKNL Padangsidimpuan'),
	 (45,'Kab. Tapanuli Selatan','KPKNL Padangsidimpuan'),
	 (46,'Kab. Padang Lawas','KPKNL Padangsidimpuan'),
	 (47,'Kab. Padang Lawas Utara','KPKNL Padangsidimpuan'),
	 (48,'Kab. Mandailing Natal','KPKNL Padangsidimpuan'),
	 (49,'Kab. Nias','KPKNL Padangsidimpuan'),
	 (50,'Kab. Nias Selatan','KPKNL Padangsidimpuan'),
	 (51,'Kab. Nias Utara','KPKNL Padangsidimpuan'),
	 (52,'Kab. Nias Barat','KPKNL Padangsidimpuan');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (53,'Kota Gunungsitoli','KPKNL Padangsidimpuan'),
	 (54,'Kota Sibolga','KPKNL Padangsidimpuan'),
	 (55,'Kab. Humbang Hasundutan','KPKNL Padangsidimpuan'),
	 (56,'Kota Pekanbaru','KPKNL Pekanbaru'),
	 (57,'Kab. Kampar','KPKNL Pekanbaru'),
	 (58,'Kab. Rokan Hulu','KPKNL Pekanbaru'),
	 (59,'Kab. Kuantan Singingi','KPKNL Pekanbaru'),
	 (60,'Kab. Indragiri Hulu','KPKNL Pekanbaru'),
	 (61,'Kab. Indragiri Hilir','KPKNL Pekanbaru'),
	 (62,'Kab. Pelalawan','KPKNL Pekanbaru');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (63,'Kota Dumai','KPKNL Dumai'),
	 (64,'Kab. Bengkalis','KPKNL Dumai'),
	 (65,'Kab. Kepulauan Meranti','KPKNL Dumai'),
	 (66,'Kab. Siak','KPKNL Dumai'),
	 (67,'Kab. Rokan Hilir','KPKNL Dumai'),
	 (68,'Kota Padang','KPKNL Padang'),
	 (69,'Kota Sawahlunto','KPKNL Padang'),
	 (70,'Kota Solak','KPKNL Padang'),
	 (71,'Kab. Solak','KPKNL Padang'),
	 (72,'Kab. Solak Selatan','KPKNL Padang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (73,'Kota Pariaman','KPKNL Padang'),
	 (74,'Kab. Padang Pariaman','KPKNL Padang'),
	 (75,'Kab. Kepulauan Mentawai','KPKNL Padang'),
	 (76,'Kab. Pesisir Selatan','KPKNL Padang'),
	 (77,'Kab. Sijunjung','KPKNL Padang'),
	 (78,'Kab. Dharmasraya','KPKNL Padang'),
	 (79,'Kota Bukittinggi','KPKNL Bukittinggi'),
	 (80,'Kota Payakumbuh','KPKNL Bukittinggi'),
	 (81,'Kota Padang Panjang','KPKNL Bukittinggi'),
	 (82,'Kab. Agam','KPKNL Bukittinggi');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (83,'Kab. Lima Puluh Kota','KPKNL Bukittinggi'),
	 (84,'Kab. Pasaman','KPKNL Bukittinggi'),
	 (85,'Kab. Pasaman Barat','KPKNL Bukittinggi'),
	 (86,'Kab. Tanah Datar','KPKNL Bukittinggi'),
	 (87,'Kota Batam','KPKNL Batam'),
	 (88,'Kab. Karimun','KPKNL Batam'),
	 (89,'Kab. Lingga','KPKNL Batam'),
	 (90,'Kota Tanjung Pinang','KPKNL Batam'),
	 (91,'Kab. Bintan','KPKNL Batam'),
	 (92,'Kab. Natuna','KPKNL Batam');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (93,'Kab. Kepulauan Anambas','KPKNL Batam'),
	 (94,'Kota Palembang','KPKNL Palembang'),
	 (95,'Kota Prabumulih','KPKNL Palembang'),
	 (96,'Kab. Banyuasin','KPKNL Palembang'),
	 (97,'Kab. Musi Banyuasin','KPKNL Palembang'),
	 (98,'Kab. Ogan Ilir','KPKNL Palembang'),
	 (99,'Kab. Ogan Komering Ulu','KPKNL Palembang'),
	 (100,'Kab. Ogan Komering Ulu Timur','KPKNL Palembang'),
	 (101,'Kab. Ogan Komering Ulu Selatan','KPKNL Palembang'),
	 (102,'Kab. Ogan Komering Ilir','KPKNL Palembang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (103,'Kab. Lahat','KPKNL Lahat'),
	 (104,'Kota Pagar Alam','KPKNL Lahat'),
	 (105,'Kota Lubuk Linggau','KPKNL Lahat'),
	 (106,'Kab. Musi Rawas','KPKNL Lahat'),
	 (107,'Kab. Muara Enim','KPKNL Lahat'),
	 (108,'Kab. Penukal Abab Lematang Ilir','KPKNL Lahat'),
	 (109,'Kab. Empat Lawang','KPKNL Lahat'),
	 (110,'Kab. Musi Rawas Utara','KPKNL Lahat'),
	 (111,'Kota Jambi','KPKNL Jambi'),
	 (112,'Kab. Batanghari','KPKNL Jambi');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (113,'Kab. Tanjung Jabung Barat','KPKNL Jambi'),
	 (114,'Kab. Tanjung Jabung Timur','KPKNL Jambi'),
	 (115,'Kab. Muaro Jambi','KPKNL Jambi'),
	 (116,'Kab. Bungo','KPKNL Jambi'),
	 (117,'Kab. Kerinci','KPKNL Jambi'),
	 (118,'Kota Sungai Penuh','KPKNL Jambi'),
	 (119,'Kab. Merangin','KPKNL Jambi'),
	 (120,'Kab. Sarolangun','KPKNL Jambi'),
	 (121,'Kab. Tebo','KPKNL Jambi'),
	 (122,'Kota Pangkal Pinang','KPKNL Pangkal Pinang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (123,'Kab. Bangka','KPKNL Pangkal Pinang'),
	 (124,'Kab. Bangka Selatan','KPKNL Pangkal Pinang'),
	 (125,'Kab. Bangka Tengah','KPKNL Pangkal Pinang'),
	 (126,'Kab. Bangka Barat','KPKNL Pangkal Pinang'),
	 (127,'Kab. Belitung','KPKNL Pangkal Pinang'),
	 (128,'Kab. Belitung Timur','KPKNL Pangkal Pinang'),
	 (129,'Kota Bandar Lampung','KPKNL Bandar Lampung'),
	 (130,'Kab. Lampung Selatan','KPKNL Bandar Lampung'),
	 (131,'Kab. Lampung Barat','KPKNL Bandar Lampung'),
	 (132,'Kab. Pesisir Barat','KPKNL Bandar Lampung');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (133,'Kab. Tanggamus','KPKNL Bandar Lampung'),
	 (134,'Kab. Pringsewu','KPKNL Bandar Lampung'),
	 (135,'Kab. Pesawaran','KPKNL Bandar Lampung'),
	 (136,'Kota Metro','KPKNL Metro'),
	 (137,'Kab. Lampung Tengah','KPKNL Metro'),
	 (138,'Kab. Lampung Timur','KPKNL Metro'),
	 (139,'Kab. Lampung Utara','KPKNL Metro'),
	 (140,'Kab. Tulang Bawang','KPKNL Metro'),
	 (141,'Kab. Tulang Bawang Barat','KPKNL Metro'),
	 (142,'Kab. Way Kanan','KPKNL Metro');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (143,'Kab. Mesuji','KPKNL Metro'),
	 (144,'Kota Bengkulu','KPKNL Bengkulu'),
	 (145,'Kab. Bengkulu Selatan','KPKNL Bengkulu'),
	 (146,'Kab. Kaur','KPKNL Bengkulu'),
	 (147,'Kab. Seluma','KPKNL Bengkulu'),
	 (148,'Kab. Rejang Lebong','KPKNL Bengkulu'),
	 (149,'Kab. Kepahiang','KPKNL Bengkulu'),
	 (150,'Kab. Lebong','KPKNL Bengkulu'),
	 (151,'Kab. Bengkulu Utara','KPKNL Bengkulu'),
	 (152,'Kab. Bengkulu Tengah','KPKNL Bengkulu');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (153,'Kab. Mukomuko','KPKNL Bengkulu'),
	 (154,'Kab. Serang','KPKNL Serang'),
	 (155,'Kota Serang','KPKNL Serang'),
	 (156,'Kota Cilegon','KPKNL Serang'),
	 (157,'Kab. Pandeglang','KPKNL Serang'),
	 (158,'Kab. Lebak','KPKNL Serang'),
	 (159,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Tangerang  I'),
	 (160,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Tangerang II'),
	 (161,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Jakarta I'),
	 (162,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Jakarta II');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (163,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Jakarta III'),
	 (164,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Jakarta IV'),
	 (165,'Pembagian Wilayah Kerja ditetapkan oleh Direktur Jenderal Kekayaan Negara','KPKNL Jakarta V'),
	 (166,'Kota Bandung','KPKNL Bandung'),
	 (167,'Kab. Bandung','KPKNL Bandung'),
	 (168,'Kab. Bandung Barat','KPKNL Bandung'),
	 (169,'Kab. Sumedang','KPKNL Bandung'),
	 (170,'Kota Cimahi','KPKNL Bandung'),
	 (171,'Kota Bekasi','KPKNL Bekasi'),
	 (172,'Kab. Bekasi','KPKNL Bekasi');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (173,'Kota Bogor','KPKNL Bogor'),
	 (174,'Kab. Bogor','KPKNL Bogor'),
	 (175,'Kota Depok','KPKNL Bogor'),
	 (176,'Kota Sukabumi','KPKNL Bogor'),
	 (177,'Kab. Sukabumi','KPKNL Bogor'),
	 (178,'Kab. Cianjur','KPKNL Bogor'),
	 (179,'Kab. Purwakarta','KPKNL Purwakarta'),
	 (180,'Kab. Subang','KPKNL Purwakarta'),
	 (181,'Kab. Karawang','KPKNL Purwakarta'),
	 (182,'Kota Tasikmalaya','KPKNL Tasikmalaya');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (183,'Kab. Tasikmalaya','KPKNL Tasikmalaya'),
	 (184,'Kota Banjar','KPKNL Tasikmalaya'),
	 (185,'Kab. Ciamis','KPKNL Tasikmalaya'),
	 (186,'Kab. Pangandaran','KPKNL Tasikmalaya'),
	 (187,'Kab. Garut','KPKNL Tasikmalaya'),
	 (188,'Kota Cirebon','KPKNL Cirebon'),
	 (189,'Kab. Cirebon','KPKNL Cirebon'),
	 (190,'Kab. Indramayu','KPKNL Cirebon'),
	 (191,'Kab. Majalengka','KPKNL Cirebon'),
	 (192,'Kab. Kuningan','KPKNL Cirebon');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (193,'Kota Semarang','KPKNL Semarang'),
	 (194,'Kab. Semarang','KPKNL Semarang'),
	 (195,'Kota Salatiga','KPKNL Semarang'),
	 (196,'Kota Magelang','KPKNL Semarang'),
	 (197,'Kab. Magelang','KPKNL Semarang'),
	 (198,'Kab. Temanggung','KPKNL Semarang'),
	 (199,'Kab. Demak','KPKNL Semarang'),
	 (200,'Kab. Grobogan','KPKNL Semarang'),
	 (201,'Kab. Kudus','KPKNL Semarang'),
	 (202,'Kab. Pati','KPKNL Semarang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (203,'Kab. Jepara','KPKNL Semarang'),
	 (204,'Kab. Blora','KPKNL Semarang'),
	 (205,'Kab. Rembang','KPKNL Semarang'),
	 (206,'Kota Surakarta','KPKNL Surakarta'),
	 (207,'Kab. Boyolali','KPKNL Surakarta'),
	 (208,'Kab. Karanganyar','KPKNL Surakarta'),
	 (209,'Kab. Klaten','KPKNL Surakarta'),
	 (210,'Kab. Sukoharjo','KPKNL Surakarta'),
	 (211,'Kab. Sragen','KPKNL Surakarta'),
	 (212,'Kab. Wonogiri','KPKNL Surakarta');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (213,'Kota Pekalongan','KPKNL Pekalongan'),
	 (214,'Kab. Pekalongan','KPKNL Pekalongan'),
	 (215,'Kab. Batang','KPKNL Pekalongan'),
	 (216,'Kab. Kendal','KPKNL Pekalongan'),
	 (217,'Kota Tegal','KPKNL Tegal'),
	 (218,'Kab. Tegal','KPKNL Tegal'),
	 (219,'Kab. Brebes','KPKNL Tegal'),
	 (220,'Kab. Pemalang','KPKNL Tegal'),
	 (221,'Kab. Banyumas','KPKNL Purwokerto'),
	 (222,'Kab. Banjarnegara','KPKNL Purwokerto');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (223,'Kab. Purbalingga','KPKNL Purwokerto'),
	 (224,'Kab. Kebumen','KPKNL Purwokerto'),
	 (225,'Kab. Cilacap','KPKNL Purwokerto'),
	 (226,'Kab. Purworejo','KPKNL Purwokerto'),
	 (227,'Kab. Wonosobo','KPKNL Purwokerto'),
	 (228,'Kota Yogyakarta','KPKNL Yogyakarta'),
	 (229,'Kab. Bantul','KPKNL Yogyakarta'),
	 (230,'Kab. Gunungkidul','KPKNL Yogyakarta'),
	 (231,'Kab. Sleman','KPKNL Yogyakarta'),
	 (232,'Kab. Kulon Progo','KPKNL Yogyakarta');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (233,'Kota Surabaya','KPKNL Surabaya'),
	 (234,'Kab. Gresik','KPKNL Surabaya'),
	 (235,'Kab. Lamongan','KPKNL Surabaya'),
	 (236,'Kab. Tuban','KPKNL Surabaya'),
	 (237,'Kab. Sidoarjo','KPKNL Sidoarjo'),
	 (238,'Kota Mojokerto','KPKNL Sidoarjo'),
	 (239,'Kab. Mojokerto','KPKNL Sidoarjo'),
	 (240,'Kota Pasuruan','KPKNL Sidoarjo'),
	 (241,'Kab. Pasuruan','KPKNL Sidoarjo'),
	 (242,'Kota Malang','KPKNL Malang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (243,'Kab. Malang','KPKNL Malang'),
	 (244,'Kota Batu','KPKNL Malang'),
	 (245,'Kota Kediri','KPKNL Malang'),
	 (246,'Kab. Kediri','KPKNL Malang'),
	 (247,'Kota Blitar','KPKNL Malang'),
	 (248,'Kab. Blitar','KPKNL Malang'),
	 (249,'Kab. Jombang','KPKNL Malang'),
	 (250,'Kab. Tulungagung','KPKNL Malang'),
	 (251,'Kab. Trenggalek','KPKNL Malang'),
	 (252,'Kab. Jember','KPKNL Jember');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (253,'Kab. Banyuwangi','KPKNL Jember'),
	 (254,'Kab. Bondowoso','KPKNL Jember'),
	 (255,'Kota Probolinggo','KPKNL Jember'),
	 (256,'Kab. Probolinggo','KPKNL Jember'),
	 (257,'Kab. Situbondo','KPKNL Jember'),
	 (258,'Kab. Lumajang','KPKNL Jember'),
	 (259,'Kab. Pamekasan','KPKNL Pamekasan'),
	 (260,'Kab. Bangkalan','KPKNL Pamekasan'),
	 (261,'Kab. Sampang','KPKNL Pamekasan'),
	 (262,'Kab. Sumenep','KPKNL Pamekasan');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (263,'Kota Madiun','KPKNL Madiun'),
	 (264,'Kab. Madiun','KPKNL Madiun'),
	 (265,'Kab. Magetan','KPKNL Madiun'),
	 (266,'Kab. Ngawi','KPKNL Madiun'),
	 (267,'Kab. Ponorogo','KPKNL Madiun'),
	 (268,'Kab. Pacitan','KPKNL Madiun'),
	 (269,'Kab. Bojonegoro','KPKNL Madiun'),
	 (270,'Kab. Nganjuk','KPKNL Madiun'),
	 (271,'Kota Pontianak',' KPKNL Pontianak'),
	 (272,'Kab. Kubu Raya',' KPKNL Pontianak');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (273,'Kab. Ketapang',' KPKNL Pontianak'),
	 (274,'Kab. Kayong Utara',' KPKNL Pontianak'),
	 (275,'Kab. Sanggau',' KPKNL Pontianak'),
	 (276,'Kab. Sekadau',' KPKNL Pontianak'),
	 (277,'Kab. Sintang',' KPKNL Pontianak'),
	 (278,'Kab. Melawi',' KPKNL Pontianak'),
	 (279,'Kab. Kapuas Hulu',' KPKNL Pontianak'),
	 (280,'Kota Singkawang',' KPKNL Singkawang'),
	 (281,'Kab. Sambas',' KPKNL Singkawang'),
	 (282,'Kab. Bengkayang',' KPKNL Singkawang');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (283,'Kab. Mempawah',' KPKNL Singkawang'),
	 (284,'Kab. Landak',' KPKNL Singkawang'),
	 (285,'Kota Banjarmasin','KPKNL Banjarmasin'),
	 (286,'Kab. Banjar','KPKNL Banjarmasin'),
	 (287,'Kab. Barito Kuala','KPKNL Banjarmasin'),
	 (288,'Kab. Tanah Laut','KPKNL Banjarmasin'),
	 (289,'Kota Banjarbaru','KPKNL Banjarmasin'),
	 (290,'Kab. Hulu Sungai Tengah','KPKNL Banjarmasin'),
	 (291,'Kab. Hulu Sungai Selatan','KPKNL Banjarmasin'),
	 (292,'Kab. Hulu Sungai Utara','KPKNL Banjarmasin');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (293,'Kab. Kotabaru','KPKNL Banjarmasin'),
	 (294,'Kab. Tabalong','KPKNL Banjarmasin'),
	 (295,'Kab. Tapin','KPKNL Banjarmasin'),
	 (296,'Kab. Balangan','KPKNL Banjarmasin'),
	 (297,'Kab. Tanah Bumbu','KPKNL Banjarmasin'),
	 (298,'Kota Palangkaraya','KPKNL Palangkaraya'),
	 (299,'Kab. Kapuas','KPKNL Palangkaraya'),
	 (300,'Kab. Pulang Pisau','KPKNL Palangkaraya'),
	 (301,'Kab. Katingan','KPKNL Palangkaraya'),
	 (302,'Kab. Barito Utara','KPKNL Palangkaraya');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (303,'Kab. Barito Selatan','KPKNL Palangkaraya'),
	 (304,'Kab. Barito Timur','KPKNL Palangkaraya'),
	 (305,'Kab. Murung Raya','KPKNL Palangkaraya'),
	 (306,'Kab. Kotawaringin Barat','KPKNL Pangkalan Bun'),
	 (307,'Kab. Kotawaringin Timur','KPKNL Pangkalan Bun'),
	 (308,'Kab. Lamandau','KPKNL Pangkalan Bun'),
	 (309,'Kab. Sukamara','KPKNL Pangkalan Bun'),
	 (310,'Kab. Seruyan','KPKNL Pangkalan Bun'),
	 (311,'Kota Balikpapan','KPKNL Balikpapan'),
	 (312,'Kab. Paser','KPKNL Balikpapan');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (313,'Kab. Penajam Paser Utara','KPKNL Balikpapan'),
	 (314,'Kota Samarinda','KPKNL Samarinda'),
	 (315,'Kab. Kutai Kartanegara','KPKNL Samarinda'),
	 (316,'Kab. Kutai Barat','KPKNL Samarinda'),
	 (317,'Kab. Mahakam Ulu','KPKNL Samarinda'),
	 (318,'Kota Bontang',' KPKNL Bontang'),
	 (319,'Kab. Kutai Timur',' KPKNL Bontang'),
	 (320,'Kab. Berau',' KPKNL Bontang'),
	 (321,'Kota Tarakan',' KPKNL Tarakan'),
	 (322,'Kab. Bulungan',' KPKNL Tarakan');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (323,'Kab. Malinau',' KPKNL Tarakan'),
	 (324,'Kab. Nunukan',' KPKNL Tarakan'),
	 (325,'Kab. Tana Tidung',' KPKNL Tarakan'),
	 (326,'Kota Denpasar','KPKNL Denpasar'),
	 (327,'Kab. Badung','KPKNL Denpasar'),
	 (328,'Kab. Gianyar','KPKNL Denpasar'),
	 (329,'Kab. Klungkung','KPKNL Denpasar'),
	 (330,'Kab. Tabanan','KPKNL Denpasar'),
	 (331,'Kab. Buleleng','KPKNL Singaraja'),
	 (332,'Kab. Bangli','KPKNL Singaraja');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (333,'Kab. Jembrana','KPKNL Singaraja'),
	 (334,'Kab. Karangasem','KPKNL Singaraja'),
	 (335,'Kota Mataram','KPKNL Mataram'),
	 (336,'Kab. Lombok Barat','KPKNL Mataram'),
	 (337,'Kab. Lombok Tengah','KPKNL Mataram'),
	 (338,'Kab. Lombok Timur','KPKNL Mataram'),
	 (339,'Kab. Lombok Utara','KPKNL Mataram'),
	 (340,'Kota Bima',' KPKNL Bima'),
	 (341,'Kab. Bima',' KPKNL Bima'),
	 (342,'Kab. Dompu',' KPKNL Bima');
INSERT INTO SIP_ABMNDEV.MASTERAREA (ID,KOTA,KPKNL) VALUES
	 (343,'Kab. Sumbawa',' KPKNL Bima'),
	 (344,'Kab. Sumbawa Barat',' KPKNL Bima'),
	 (345,'Kota Kupang',' KPKNL Kupang'),
	 (346,'Kab. Kupang',' KPKNL Kupang'),
	 (347,'Kab. Belu',' KPKNL Kupang'),
	 (348,'Kab. Malaka',' KPKNL Kupang'),
	 (349,'Kab. Alor',' KPKNL Kupang'),
	 (350,'Kab. Sumba Barat',' KPKNL Kupang'),
	 (351,'Kab. Sumba Tengah',' KPKNL Kupang'),
	 (352,'Kab. Sumba Barat Daya',' KPKNL Kupang');
